import is from '../../utils/is';

class Shopify {

  static getShopDomain() {
    if (!is.empty(window.Shopify?.shop)) {
      return window.Shopify.shop;
    }

    return document.domain;
  }

  static getProductId() {
    if (is.empty(window.meta?.product?.id)) {
      return null;
    }
    return window.meta.product.id;
  }

  /**
   * Get locale from a pathname
   * @param {string} [aPath]
   * @return {null|string}
   */
  static getLocale(aPath) {
    const path = aPath || window.location.pathname;
    let pathParts = path.split('/');
    pathParts = pathParts.splice(1, pathParts.length);

    const localeRegexCase1 = /^[a-zA-Z]{2}$/;
    const localeRegexCase2 = /^[a-zA-Z]{2}-[a-zA-Z]{2}$/;
    const locale = pathParts[0].match(localeRegexCase1) ||
      pathParts[0].match(localeRegexCase2);

    if (locale === null) {
      return null;
    }

    return locale[0];
  }

  static isHomepage(aPath) {
    const path = aPath || window.location.pathname;
    const locale = Shopify.getLocale(path);

    return path === '/' || path === `/${locale}` || path === `/${locale}/`;
  }

  /**
   * Browsers have an extended list of supported languages, some not supported in Shopify yet
   * @param {string} language
   * @return {string|null}
   */
  static mapBrowserLanguageToShopifyLocale(language) {
    switch (language) {
      case 'zh-HK':
        return 'zh-TW';
      default:
        return '';
    }
  }

  // Get the forms generated by Geolocation by Shopify
  // https://apps.shopify.com/geolocation
  static getGeolocationByShopifyForms() {
    const formSelectors = [
      '.locale-bar__form',
      '.locale-selectors__container form',
    ];
    let forms = [];

    formSelectors.forEach(selector => {
      const elms = Array.from(document.querySelectorAll(selector));
      forms = forms.concat(elms);
    });

    return forms;
  }

  /**
   * @return {string}
   */
  static getCurrentRegion() {
    if (!is.string(window.Shopify?.country)) {
      return '';
    }
    return window.Shopify.country;
  }

  /**
   * @return {string}
   */
  static getCurrentLanguage() {
    if (!is.string(window.Shopify?.locale)) {
      return '';
    }
    return window.Shopify.locale;
  }

}

export default Shopify;


