import is from '../../utils/is';

class Shopify {

  /**
   * @returns {string}
   */
  static shopDomain() {
    if (!is.empty(window.Shopify?.shop)) {
      return window.Shopify.shop;
    }

    return document.domain;
  }

  /**
   * @returns {number}
   */
  static productId() {
    if (is.empty(window.meta?.product?.id)) {
      return -1;
    }
    return window.meta.product.id;
  }

  /**
   * @param {string} [aPath]
   * @return {string}
   */
  static languageInPathname(aPath) {
    const path = aPath || window.location.pathname;
    let pathParts = path.split('/');
    pathParts = pathParts.splice(1, pathParts.length);

    const localeRegexCase1 = /^[a-zA-Z]{2}$/;
    const localeRegexCase2 = /^[a-zA-Z]{2}-[a-zA-Z]{2}$/;
    const locale = pathParts[0].match(localeRegexCase1) ||
      pathParts[0].match(localeRegexCase2);

    if (locale === null) {
      return '';
    }

    return locale[0];
  }

  static isHomepage(aPath) {
    const path = aPath || window.location.pathname;
    const locale = Shopify.languageInPathname(path);

    return path === '/' || path === `/${locale}` || path === `/${locale}/`;
  }

  /**
   * Browsers have an extended list of supported languages, some not supported in Shopify yet
   * @param {string} language
   * @return {string|null}
   */
  static mapBrowserLanguageToShopifyLanguage(language) {
    switch (language) {
      case 'zh-HK':
        return 'zh-TW';
      default:
        return '';
    }
  }

  // Get the forms generated by Geolocation by Shopify
  // https://apps.shopify.com/geolocation
  static getGeolocationByShopifyForms() {
    const formSelectors = [
      '.locale-bar__form',
      '.locale-selectors__container form',
    ];
    let forms = [];

    formSelectors.forEach(selector => {
      const elms = Array.from(document.querySelectorAll(selector));
      forms = forms.concat(elms);
    });

    return forms;
  }

  /**
   * @return {string}
   */
  static currentRegion() {
    if (!is.string(window.Shopify?.country)) {
      return '';
    }
    return window.Shopify.country;
  }

  /**
   * @return {string}
   */
  static currentLanguage() {
    if (!is.string(window.Shopify?.locale)) {
      return '';
    }
    return window.Shopify.locale;
  }

  /**
   * Get pathname with search excluding locale
   * @return {string}
   */
  static pathnameWithSearch() {
    const { pathname, search = '' } = window.location;
    if (is.nullOrUndefined(pathname)) {
      throw new Error(`Expect a pathname but got ${pathname}`);
    }
    const locale = Shopify.languageInPathname(pathname);
    if (is.empty(locale)) {
      return pathname + search;
    }
    if (pathname === `/${locale}`) {
      return '/';
    }

    return pathname.replace(`/${locale}`, '') + search;
  }

}

export default Shopify;


